version: '3.8'  # Adjust if needed

services:
  flask_app:
    build:
      context: .  # Set this to the root directory containing both Flask_App and Dockerfile
      dockerfile: ./Flask_App/Dockerfile  # Path to the Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
    volumes:
      - ./Flask_App:/app

  postgres:
    image: postgres:13
    ports:
      - "7777:5432"
    environment:
      POSTGRES_DB: primal_health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

volumes:
  postgres_data:
