services:
  
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: primal_health
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  flask_app:
    build:
      context: .  # Set this to the root directory containing both Flask_App and Dockerfile
      dockerfile: ./Flask_App/Dockerfile  # Path to the Dockerfile
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FLASK_APP: ${FLASK_APP}
      project_path: ${Project_Path}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      
    depends_on:
      - postgres
    volumes:
      - ./Flask_App:/app
      - ./data/clean_data:/app/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3100:3000"
    depends_on:
      - postgres
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  grafana_data:
